'use client';

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Plus, Minus } from 'lucide-react';

const faqs = [
  {
    question: "Can I edit the generated resume and content?",
    answer: "Absolutely. Everything generated by GetProspectra is fully editable. You can tweak bullets, rearrange sections, and customize the layout before downloading or publishing."
  },
  {
    question: "What happens after I upgrade to Premium?",
    answer: "Upon upgrading, you immediately unlock all premium portfolio templates, advanced interview prep questions, and the ability to generate 3 targeted resume variations from your single profile."
  },
  {
    question: "Is my data safe and secure?",
    answer: "Yes. We take privacy seriously. Your career data is encrypted and only used to generate your personal assets. We never sell your information to third parties."
  },
  {
    question: "Can I use my own domain for the portfolio?",
    answer: "Currently, portfolios are hosted on a premium GetProspectra subdomain (e.g., yourname.getprospectra.com). Custom domain mapping is coming in our next major update!"
  },
  {
    question: "Can I create multiple profiles?",
    answer: "Yes, you can manage multiple career profiles under a single account if you are pivoting careers or want drastically different positioning for different industries."
  },
  {
    question: "Can I download my resume and content?",
    answer: "Yes, you can instantly export your generated resumes as ATS-friendly PDFs. You can also export your interview prep kits."
  },
  {
    question: "How accurate is the AI content generation?",
    answer: "Unlike standard AI writers that hallucinate, our engine relies strictly on the facts you provide in your Career Profile. It focuses on restructuring for impact rather than making things up."
  },
  {
    question: "Do you offer refunds?",
    answer: "We offer a generous free tier so you can fully experience the platform before upgrading. Because of this, premium upgrades are generally non-refundable."
  },
  {
    question: "How is this different from other tools?",
    answer: "Traditional builders just give you templates. We give you an ecosystem. You enter data once, and we generate a cohesive resume, website, and interview kit that all perfectly align."
  }
];

function AccordionItem({ faq, isOpen, onClick }: { faq: any, isOpen: boolean, onClick: () => void }) {
  return (
    <div className="border border-[var(--color-v2-border)] bg-white rounded-xl overflow-hidden mb-4 transition-shadow hover:shadow-sm">
      <button 
        className="w-full px-6 py-5 flex items-center justify-between text-left"
        onClick={onClick}
      >
        <span className="font-bold text-[var(--color-v2-text-primary)] text-sm pr-8">{faq.question}</span>
        <div className="shrink-0 w-8 h-8 rounded-full border border-[var(--color-v2-border)] flex items-center justify-center text-[var(--color-v2-text-secondary)]">
          {isOpen ? <Minus size={14} /> : <Plus size={14} />}
        </div>
      </button>
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3, ease: "easeInOut" }}
          >
            <div className="px-6 pb-6 text-sm text-[var(--color-v2-text-secondary)] leading-relaxed">
              {faq.answer}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export default function FAQSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  // Split FAQs into two columns
  const midPoint = Math.ceil(faqs.length / 2);
  const leftCol = faqs.slice(0, midPoint);
  const rightCol = faqs.slice(midPoint);

  return (
    <section id="faq" className="w-full py-32 bg-[var(--color-v2-bg)]">
      <div className="max-w-[1400px] mx-auto px-6 lg:px-12">
        
        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest text-[var(--color-v2-primary)] mb-4">
            Frequently Asked Questions
          </div>
          <h2 className="text-4xl md:text-5xl font-serif font-black text-[var(--color-v2-text-primary)] tracking-tight">
            Everything You Need to Know
          </h2>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 items-start">
          <div>
            {leftCol.map((faq, idx) => (
              <AccordionItem 
                key={idx} 
                faq={faq} 
                isOpen={openIndex === idx} 
                onClick={() => toggleFAQ(idx)} 
              />
            ))}
          </div>
          <div>
            {rightCol.map((faq, idx) => (
              <AccordionItem 
                key={idx + midPoint} 
                faq={faq} 
                isOpen={openIndex === (idx + midPoint)} 
                onClick={() => toggleFAQ(idx + midPoint)} 
              />
            ))}
          </div>
        </div>

      </div>
    </section>
  );
}
